In [1]:
import pandas as pd
import numpy as np

concrete_data= pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [2]:
concrete_data.shape

(1030, 9)

In [3]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [4]:
concrete_data_columns= concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns!= 'Strength']]
target = concrete_data['Strength']

In [5]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [6]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Now we need to normalize the data

In [7]:

predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [8]:
n_cols = predictors_norm.shape[1] # number of predictors
n_cols

8

In [9]:
import keras

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [10]:
from keras.models import Sequential
from keras.layers import Dense

In [11]:
# Build a Baseline Model

def regression_model():

  model = Sequential()
  model.add(Dense(10, activation='relu', input_shape =(n_cols,)))
  model.add(Dense(10, activation='relu'))
  model.add(Dense(10, activation='relu'))
 
  model.add(Dense(1))
    
  model.compile(optimizer='adam', loss='mean_squared_error')
  return model

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3,random_state=42)

In [14]:
#build the model

model = regression_model()

In [15]:
#fit the model

epochs = 50
model.fit(X_train,y_train,epochs=epochs, verbose=1)

Epoch 1/50
721/721 [==============================] - ETA: 0s - loss: 1547.86 - 1s 1ms/step - loss: 1551.3866
Epoch 2/50
721/721 [==============================] - 0s 614us/step - loss: 1505.6876
Epoch 3/50
721/721 [==============================] - 0s 659us/step - loss: 1439.8109
Epoch 4/50
721/721 [==============================] - 0s 637us/step - loss: 1345.5688
Epoch 5/50
721/721 [==============================] - 0s 581us/step - loss: 1219.8222
Epoch 6/50
721/721 [==============================] - 0s 611us/step - loss: 1050.2889
Epoch 7/50
721/721 [==============================] - 0s 636us/step - loss: 837.3850
Epoch 8/50
721/721 [==============================] - 0s 553us/step - loss: 604.0052
Epoch 9/50
721/721 [==============================] - 0s 560us/step - loss: 414.8511
Epoch 10/50
721/721 [==============================] - 1s 720us/step - loss: 310.6635 0s - loss: 322.28
Epoch 11/50
721/721 [==============================] - 0s 692us/step - loss: 265.6154
Epoch 12/50
721/721 [==============================] - 0s 613us/step - loss: 241.2665
Epoch 13/50
721/721 [==============================] - 0s 590us/step - loss: 225.2419
Epoch 14/50
721/721 [==============================] - 0s 573us/step - loss: 212.0996
Epoch 15/50
721/721 [==============================] - 0s 637us/step - loss: 202.5860
Epoch 16/50
721/721 [==============================] - 0s 635us/step - loss: 194.2050
Epoch 17/50
721/721 [==============================] - 0s 527us/step - loss: 187.9810
Epoch 18/50
721/721 [==============================] - 0s 642us/step - loss: 182.3203
Epoch 19/50
721/721 [==============================] - 1s 825us/step - loss: 177.5701
Epoch 20/50
721/721 [==============================] - 0s 663us/step - loss: 173.5950
Epoch 21/50
721/721 [==============================] - 0s 666us/step - loss: 170.1599
Epoch 22/50
721/721 [==============================] - 0s 607us/step - loss: 166.9959
Epoch 23/50
721/721 [==============================] - 0s 636us/step - loss: 164.0841
Epoch 24/50
721/721 [==============================] - 0s 636us/step - loss: 161.4346
Epoch 25/50
721/721 [==============================] - 0s 636us/step - loss: 159.2322
Epoch 26/50
721/721 [==============================] - 1s 747us/step - loss: 157.1281
Epoch 27/50
721/721 [==============================] - 0s 611us/step - loss: 155.3296
Epoch 28/50
721/721 [==============================] - 0s 581us/step - loss: 153.5358 0s - loss: 160.
Epoch 29/50
721/721 [==============================] - 0s 579us/step - loss: 152.2339
Epoch 30/50
721/721 [==============================] - 0s 637us/step - loss: 150.8346
Epoch 31/50
721/721 [==============================] - 0s 638us/step - loss: 149.7125
Epoch 32/50
721/721 [==============================] - 0s 612us/step - loss: 148.2764
Epoch 33/50
721/721 [==============================] - 0s 668us/step - loss: 147.0605
Epoch 34/50
721/721 [==============================] - 0s 612us/step - loss: 145.4589
Epoch 35/50
721/721 [==============================] - 1s 717us/step - loss: 144.2464
Epoch 36/50
721/721 [==============================] - 1s 696us/step - loss: 143.0659
Epoch 37/50
721/721 [==============================] - 0s 578us/step - loss: 141.8936
Epoch 38/50
721/721 [==============================] - 0s 577us/step - loss: 141.0960
Epoch 39/50
721/721 [==============================] - 0s 692us/step - loss: 139.7564
Epoch 40/50
721/721 [==============================] - 0s 635us/step - loss: 138.6259
Epoch 41/50
721/721 [==============================] - 0s 607us/step - loss: 137.4725
Epoch 42/50
721/721 [==============================] - 1s 718us/step - loss: 136.6126
Epoch 43/50
721/721 [==============================] - 0s 618us/step - loss: 135.0898
Epoch 44/50
721/721 [==============================] - 0s 655us/step - loss: 134.1116
Epoch 45/50
721/721 [==============================] - 1s 747us/step - loss: 132.8515
Epoch 46/50
721/721 [==============================] - 0s 665us/step - loss: 132.0825
Epoch 47/50
721/721 [==============================] - 0s 631us/step - loss: 130.4987
Epoch 48/50
721/721 [==============================] - 0s 635us/step - loss: 129.5439 0s - loss: 131.124
Epoch 49/50
721/721 [==============================] - 0s 583us/step - loss: 128.6460
Epoch 50/50
721/721 [==============================] - 0s 634us/step - loss: 127.4922

In [16]:
loss_val = model.evaluate(X_test, y_test)
y_pred= model.predict(X_test)

309/309 [==============================] - 0s 451us/step

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
mean_sq_error = mean_squared_error(y_test,y_pred)
mean = np.mean(mean_sq_error)
standard_dev = np.std(mean_sq_error)
print(mean,standard_dev)

127.42086598606596 0.0

In [ ]:
total_mean_squared_errors = 50
epochs = 100
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors without normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 44.98975346389326
MSE 2: 48.19310769139756
MSE 3: 37.394463838497025
MSE 4: 37.61824023299233