In [1]:
import pandas as pd
import numpy as np

concrete_data= pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [2]:
concrete_data.shape

(1030, 9)

In [3]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [4]:
concrete_data_columns= concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns!= 'Strength']]
target = concrete_data['Strength']

In [5]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [6]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [7]:
n_cols = predictors.shape[1] # number of predictors
n_cols

8

In [8]:
import keras

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [9]:
from keras.models import Sequential
from keras.layers import Dense

In [10]:
# Build a Baseline Model

def regression_model():

  model = Sequential()
  model.add(Dense(10, activation='relu', input_shape =(n_cols,)))
  model.add(Dense(1))
    
  model.compile(optimizer='adam', loss='mean_squared_error')
  return model

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3,random_state=42)

In [13]:
#build the model

model = regression_model()

In [14]:
#fit the model

epochs = 50
model.fit(X_train,y_train,epochs=epochs, verbose=1)

Epoch 1/50
721/721 [==============================] - 1s 966us/step - loss: 2259.8121
Epoch 2/50
721/721 [==============================] - 0s 380us/step - loss: 1176.3843
Epoch 3/50
721/721 [==============================] - 0s 442us/step - loss: 977.7475
Epoch 4/50
721/721 [==============================] - 0s 391us/step - loss: 859.1988
Epoch 5/50
721/721 [==============================] - 0s 467us/step - loss: 759.9908
Epoch 6/50
721/721 [==============================] - 0s 440us/step - loss: 668.5244
Epoch 7/50
721/721 [==============================] - 0s 441us/step - loss: 590.9987
Epoch 8/50
721/721 [==============================] - 0s 468us/step - loss: 523.3589
Epoch 9/50
721/721 [==============================] - ETA: 0s - loss: 472.396 - 0s 497us/step - loss: 466.1548
Epoch 10/50
721/721 [==============================] - 0s 440us/step - loss: 418.9152
Epoch 11/50
721/721 [==============================] - 0s 473us/step - loss: 371.0928
Epoch 12/50
721/721 [==============================] - 0s 416us/step - loss: 331.2697
Epoch 13/50
721/721 [==============================] - 0s 441us/step - loss: 299.5660
Epoch 14/50
721/721 [==============================] - 0s 388us/step - loss: 274.5838
Epoch 15/50
721/721 [==============================] - 0s 560us/step - loss: 246.4380
Epoch 16/50
721/721 [==============================] - 0s 387us/step - loss: 228.4507
Epoch 17/50
721/721 [==============================] - 0s 415us/step - loss: 210.4728
Epoch 18/50
721/721 [==============================] - 0s 448us/step - loss: 195.4133
Epoch 19/50
721/721 [==============================] - 0s 584us/step - loss: 183.7295
Epoch 20/50
721/721 [==============================] - 0s 418us/step - loss: 171.5792
Epoch 21/50
721/721 [==============================] - 0s 437us/step - loss: 165.0632
Epoch 22/50
721/721 [==============================] - 0s 385us/step - loss: 156.7294
Epoch 23/50
721/721 [==============================] - 0s 387us/step - loss: 149.6239
Epoch 24/50
721/721 [==============================] - 0s 418us/step - loss: 148.2986
Epoch 25/50
721/721 [==============================] - 0s 505us/step - loss: 140.2449
Epoch 26/50
721/721 [==============================] - 0s 446us/step - loss: 135.4770
Epoch 27/50
721/721 [==============================] - 0s 390us/step - loss: 133.0188
Epoch 28/50
721/721 [==============================] - 0s 409us/step - loss: 132.0798
Epoch 29/50
721/721 [==============================] - 0s 417us/step - loss: 128.3540
Epoch 30/50
721/721 [==============================] - 0s 361us/step - loss: 126.7418
Epoch 31/50
721/721 [==============================] - 0s 472us/step - loss: 126.5227
Epoch 32/50
721/721 [==============================] - 0s 390us/step - loss: 125.3082
Epoch 33/50
721/721 [==============================] - 0s 330us/step - loss: 123.5582
Epoch 34/50
721/721 [==============================] - 0s 438us/step - loss: 118.7794
Epoch 35/50
721/721 [==============================] - 0s 442us/step - loss: 118.8146
Epoch 36/50
721/721 [==============================] - 0s 472us/step - loss: 117.0558
Epoch 37/50
721/721 [==============================] - 0s 442us/step - loss: 117.9468
Epoch 38/50
721/721 [==============================] - 0s 501us/step - loss: 118.7861
Epoch 39/50
721/721 [==============================] - 0s 527us/step - loss: 114.4083
Epoch 40/50
721/721 [==============================] - 0s 428us/step - loss: 115.9376
Epoch 41/50
721/721 [==============================] - 0s 443us/step - loss: 113.7086
Epoch 42/50
721/721 [==============================] - 0s 496us/step - loss: 113.4524
Epoch 43/50
721/721 [==============================] - 0s 387us/step - loss: 116.8314
Epoch 44/50
721/721 [==============================] - 0s 525us/step - loss: 113.1835
Epoch 45/50
721/721 [==============================] - 0s 468us/step - loss: 113.7432
Epoch 46/50
721/721 [==============================] - 0s 386us/step - loss: 112.9561
Epoch 47/50
721/721 [==============================] - 0s 448us/step - loss: 111.8605
Epoch 48/50
721/721 [==============================] - 0s 482us/step - loss: 112.0853
Epoch 49/50
721/721 [==============================] - 0s 392us/step - loss: 111.4230
Epoch 50/50
721/721 [==============================] - 0s 467us/step - loss: 111.9688

In [15]:
loss_val = model.evaluate(X_test, y_test)
y_pred= model.predict(X_test)

309/309 [==============================] - 0s 378us/step

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
mean_sq_error = mean_squared_error(y_test,y_pred)
mean = np.mean(mean_sq_error)
standard_dev = np.std(mean_sq_error)
print(mean,standard_dev)

111.39235530908189 0.0

In [19]:
total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors without normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 93.64691575676878
MSE 2: 121.05390204272224
MSE 3: 108.3949256822901
MSE 4: 122.20214900538373
MSE 5: 122.28747484521958
MSE 6: 107.8368657676919
MSE 7: 129.56470482094775
MSE 8: 98.22892504448258
MSE 9: 119.05060836643848
MSE 10: 118.208397775792
MSE 11: 103.49955502605746
MSE 12: 101.41784487727391
MSE 13: 116.43787072931678
MSE 14: 115.67075636780378
MSE 15: 120.17928450007268
MSE 16: 107.10304378768772
MSE 17: 105.68797410884721
MSE 18: 95.89555845291483
MSE 19: 110.35192379750866
MSE 20: 114.02160871684744
MSE 21: 97.06264295855772
MSE 22: 102.8476325470267
MSE 23: 107.1684174275321
MSE 24: 105.93955568974071
MSE 25: 110.76302624057412
MSE 26: 99.37680177163924
MSE 27: 125.19529299442821
MSE 28: 111.73397434567943
MSE 29: 109.62652165681413
MSE 30: 113.20150349441084
MSE 31: 133.8339912636766
MSE 32: 107.5850936371146
MSE 33: 105.42392096164542
MSE 34: 109.06704840305167
MSE 35: 115.89580607491403
MSE 36: 126.59050802582676
MSE 37: 119.06043245877262
MSE 38: 127.22944875673954
MSE 39: 109.29892683800756
MSE 40: 115.65188778874172
MSE 41: 119.03596360783747
MSE 42: 111.5277626506719
MSE 43: 108.48334932790219
MSE 44: 106.99177766077727
MSE 45: 117.64721709316217
MSE 46: 115.76457525456993
MSE 47: 113.2099406418291
MSE 48: 115.31672520313448
MSE 49: 102.15841420491536
MSE 50: 122.62240659843371


Below is the mean and standard deviation of 50 mean squared errors without normalized data. Total number of epochs for each training is: 50

Mean: 112.32101582098066
Standard Deviation: 8.941637323121805